# Generated by Django 5.2.6 on 2025-09-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='hero_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Product_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Rating',
        ),
        migrations.AddField(
            model_name='user',
            name='header_sections',
            field=models.JSONField(default=list),
        ),
    ]
