# Generated by Django 5.2.6 on 2025-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_image_user_hero_image_remove_user_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Api', 'verbose_name_plural': 'Api'},
        ),
    ]
