# Generated by Django 5.2.6 on 2025-10-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_brand_remove_product_is_favorite_product_brand_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
