# Generated by Django 5.2.6 on 2025-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_offer_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer',
            field=models.IntegerField(null=True),
        ),
    ]
