# Generated by Django 5.2.6 on 2025-10-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_product_alter_cart_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
