# Generated by Django 5.2.6 on 2025-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids')], max_length=300),
        ),
    ]
