# Generated by Django 5.2.6 on 2025-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_heroimage_herobutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobutton',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
