# Generated by Django 5.2.6 on 2025-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('is_active', models.BooleanField(default=True)),
                ('filter_by', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
