# Generated by Django 5.2.6 on 2025-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_herobutton_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
