# Generated by Django 5.2.6 on 2025-09-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_offer_offer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Api',
        ),
    ]
