# Generated by Django 5.2.6 on 2026-06-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_notification_product_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
