# Generated by Django 5.2.6 on 2025-09-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
