# Generated by Django 5.2.6 on 2026-06-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Office', 'Office'), ('Luxry', 'Luxry'), ('Home', 'Home'), ('Carpet', 'Carpet'), ('Rug', 'Rug')], max_length=300),
        ),
    ]
