# Generated by Django 5.2.6 on 2025-10-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_catagory_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
