# Generated by Django 5.2.6 on 2026-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_category_name_productsize_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['length_cm', 'width_cm']},
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='length',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='width',
        ),
        migrations.AddField(
            model_name='productsize',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='length_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='width_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
