# Generated by Django 5.2.6 on 2026-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_productsize_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
