# Generated by Django 5.2.6 on 2026-08-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_productsize_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
